# 监控的 AUR 包列表
packages:
  - visual-studio-code-bin
  - opencode-desktop-bin
  - claude-code
  - openai-codex-bin
  - hysteria-bin
  - localsend-bin
  # - clash-verge-rev-autobuild-bin
  # - wechat-universal-bwrap
  # - wemeet-bin
  # - dingtalk-bin
  # - baidunetdisk-bin
