name = "archlinux-repo"

workers_dev = true
compatibility_date = "2025-05-04"

main = "index.js"

dev.host = "127.0.0.1"
dev.port = 8012

[[r2_buckets]]
binding = "ARCH_REPO"
bucket_name = "archlinux-repo"