name: 'Generator pacman package database'
description: 'Generator pacman package database in Docker container'
branding:
  icon: user-check
  color: gray-dark
inputs:
  database:
    description: 'AUR repository database name'
    required: true
    default: 'self'
  path:
    description: 'packages dir'
    required: true
    default: './repo/'
  gpg-private-key:
    description: 'GPG private key'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DATABASE: ${{ inputs.database }}
    PACKAGE_PATH: ${{ inputs.path }}
    GPG_PRIVATE_KEY: ${{ inputs.gpg-private-key }}