name: 'Generator pacman package database'
description: 'Generator pacman package database in Docker container'
branding:
  icon: user-check
  color: gray-dark
inputs:
  database:
    description: 'AUR repository database name'
    required: true
    default: 'self'
  path:
    description: 'packages dir'
    required: true
    default: './repo/'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.database }}
    - ${{ inputs.path }}